### ISSUE TITLE
Building on macOS is problematic

### ISSUE THREAD

**Issue by flipphillips** [OneNoteDev/WebClipper#446]
Building on macOS is breaking. 

Configuration-
macOS 10.14.5 Mojave
npm 6.9.0

Steps-
1. fresh clone
2. npm install
3. npm build

Expected-
No worldly problems at all building :)

Actual-
1. `npm install` makes following complaints -
```bash
(base) purkinje:WebClipper> npm install

> fsevents@1.2.4 install /Users/flip/GitHub/WebClipper/node_modules/fsevents
> node install
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.4/fse-v1.2.4-node-v72-darwin-x64.tar.gz
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.4 and node@12.3.1 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
...
...
                                                         ;
30 warnings and 15 errors generated.
make: *** [fse.target.mk:129: Release/obj.target/fse/fsevents.o] Error 1
make: Leaving directory '/Users/flip/GitHub/WebClipper/node_modules/fsevents/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.6.0
gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64" "--napi_version=4" "--node_abi_napi=napi"
gyp ERR! cwd /Users/flip/GitHub/WebClipper/node_modules/fsevents
gyp ERR! node -v v12.3.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/flip/GitHub/WebClipper/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
node-pre-gyp ERR! System Darwin 18.6.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/12.3.1/bin/node" "/Users/flip/GitHub/WebClipper/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/flip/GitHub/WebClipper/node_modules/fsevents
node-pre-gyp ERR! node -v v12.3.1
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/local/Cellar/node/12.3.1/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/flip/GitHub/WebClipper/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)

> phantomjs-prebuilt@2.1.16 install /Users/flip/GitHub/WebClipper/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/nb/zmfwvqz937zbd72kshwnqnv80000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [----------------------------------------] 0%
Received 16746K total.
Extracting zip contents
Removing /Users/flip/GitHub/WebClipper/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/nb/zmfwvqz937zbd72kshwnqnv80000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1559573617217/phantomjs-2.1.1-macosx -> /Users/flip/GitHub/WebClipper/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/flip/GitHub/WebClipper/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: hwa@0.0.7 (node_modules/hwa):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for hwa@0.0.7: wanted {"os":"win32","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1424 packages from 1328 contributors and audited 8617 packages in 17.766s
found 179 vulnerabilities (27 low, 121 moderate, 27 high, 4 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
```

2. `npm build` yields
```

> webclipper@3.8.1 build /Users/flip/GitHub/WebClipper
> gulp build

fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/flip/GitHub/WebClipper/node_modules/natives/index.js:137:5)
    at Object.req [as require] (/Users/flip/GitHub/WebClipper/node_modules/natives/index.js:54:10)
    at Object.<anonymous> (/Users/flip/GitHub/WebClipper/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webclipper@3.8.1 build: `gulp build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webclipper@3.8.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Please forgive any obviously stupid things as I have very little intuitive understanding of the whole `npm` scene. Just following directions in the `README.md`

**Comment by JosiahThobejane** [comment]
I am also facing the same problem and on a Mac, I have tried downgrading my Gulp to 3.9.1 but that gave me the second problem (2.) that you are facing.

Have you by any chance been able to solve this?

**Comment by JosiahThobejane** [comment]
@flipphillips I was able to get it to run in `npm run build-only` 

To get there I had to downgrade both by local and global gulp to 3.9.1, also downgrade Node to v10.16.0, then deal with like 2 more issues after that, on the first issue you will have to downgrade a package then on the other issue you will have to import a new package and run npm build. All should then be well :) , shout if you may need assistance

**Comment by flipphillips** [comment]
@JosiahThobejane - beautiful- I will give this a try. Thanks for the leg-work!
